### ISSUE TITLE
New version Notification

### ISSUE THREAD

**Issue by KyleMartin901** [pivotal-cf/pivnet-resource#105]
Hi,

Just looking for some help. 

I would love it if I could send the new version number of the product that is being downloaded in a slack notification.

The output in the concourse web UI contains the info I am after just wondering what would be the best way to get that info to send in the slack notification or just any notification

availability | All Users
-- | --
controlled | false
description | Please refer to the release notes
eccn | 5D002c.1 740.17b.1
end_of_availability_date |  
end_of_guidance_date |  
end_of_support_date | 2019-06-30
license_exception | ENC
release_date | 2018-10-25
release_notes_url | https://docs.pivotal.io/pivotalcf/2.3/pcf-release-notes/runtime-rn.html
release_type | Security Release
version | 2.3.2

**Comment by KyleMartin901** [comment]
Thanks Paul,

Just learning concourse and saw the nice output in the console and was hoping I could set it to output to a file that I could then use in the slack resource.

**Comment by robdimsdale** [comment]
@KyleMartin901 if you want the specific example:

> new version number of the product that is being downloaded

or the metadata in the table you described, then this is written to files during download.

You would be able to write a small task to extract the information you need from this, and feed it into the [slack notification resource](https://github.com/cloudfoundry-community/slack-notification-resource).

The suggestions by @pnikonowicz would enable you to scrape the output, which would probably include the information you need, but would probably be more complicated to setup and maintain.

If the metadata files don't contain what you need, you could open an issue to discuss your needs.

**Comment by KyleMartin901** [comment]
Thanks heaps @robdimsdale 

Not sure how I missed that as its on the from page :(

>The metadata for the product is written to both metadata.json and metadata.yaml in the working directory (typically /tmp/build/get). Use this to programmatically determine metadata of the release.

It also should of clicked to check the [pcf-pipelines](https://github.com/pivotal-cf/pcf-pipelines) tasks like the [upload-product-and-stemcell](https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/upload-product-and-stemcell/task.sh) as I can see how it is used there to find the details using the metadata.json file.
