### ISSUE TITLE
latest-final release doesn't include 'unzip'

### ISSUE THREAD

**Issue by iamtpage** [pivotal-cf/pivnet-resource#111]
Hi,

We were using `latest-final` and with the latest release, it seems that `unzip` is not included in the image or not included in the `$PATH`. We verified this by hijacking a container using the latest release and running `which unzip`, which returns nothing. Running any concourse tasks that use the `pivnet_resource` fails when trying to unzip a file:

```
ERROR: failed to extract archive: exec: "unzip": executable file not found in $PATH with mimetype application/zip
```

Reverting to `v0.31.17` fixes this issue.

**Comment by sigilite** [comment]
Thanks for bringing this to our attention-- the unzip issue should be fixed in `v0.31.19`.
