### ISSUE TITLE
Handling flakes from PivNet/CDN

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/pivnet-resource#113]
CF Toolsmiths are downloading ~5,000 OpsManager OVAs via the pivnet-resource each month. We have found that 5-10 times per month, we get the following flakes from PivNet/CDN:

```
2019/03/14 20:02:19 PivNet Resource version: 0.31.21
2019/03/14 20:02:19 Creating download directory: /tmp/build/get
2019/03/14 20:02:19 Getting release for product slug: 'ops-manager' and product version: '2.1.20'
2019/03/14 20:02:20 Exiting with error: failed to fetch API token - received status 405
```

or 

```
2019/03/14 20:02:33 PivNet Resource version: 0.31.21
2019/03/14 20:02:33 Creating download directory: /tmp/build/get
2019/03/14 20:02:33 Getting release for product slug: 'ops-manager' and product version: '2.1.20'
2019/03/14 20:02:33 Exiting with error: failed to fetch API token - received status 404
```

We currently have `attempts: 5` on the task itself, but we've found it will still fail 5 times in a row. Our concourse server also triggers tasks fairly quickly. We've found that if we manually re-trigger the job, several minutes later, the job will be successful. We do not believe there is anything mis-configured on the job.

We are thinking that if we occasionally hit issues like this, our customers using platform automation tooling will likely hit the same issues.

**Modest Proposal**
Maybe the PivNet resource could have some back-off logic, so that it sleeps for some period of time before re-trying? We've successfully implemented this logic using the PivNet CLI when downloading the PAS tile.

`  [[ ${tries} -gt 0 ]] && echo "pivnet-cli login - waiting 5 mins for next try" && sleep 300`

Alternatively, we could use the PivNet CLI for downloading the OpsMan OVA too, but that wouldn't help end customers who may also run into this issue.

Thanks,
Mike J
PM@CF Toolsmiths

**Comment by pnikonowicz** [comment]
Is it possible to turn add the [verbose](https://github.com/pivotal-cf/pivnet-resource/blob/330a394a90bd0c9042deea56d4ec92c67832a9cf/concourse/types.go#L19) flag to your configuration and resend the error you are getting? 
I'd like to know where in the `out` command that the error occurs.

**Comment by mjj209** [comment]
We can add the verbose flag sometime next week. Here's our story: https://www.pivotaltracker.com/story/show/164674719 I'll update this issue when/if we get another failure.

**Comment by rszumlakowski** [comment]
Hi @mjj209 .  I'm just following up with you to see if you still need help with this issue.
