### ISSUE TITLE
Blocking issue on downloading a xenia stemcell with the latest release of pivnet-resource

### ISSUE THREAD

**Issue by erboucherie** [pivotal-cf/pivnet-resource#114]
We try to download a xenia stemcell with the following command : `pivnet-cli download-product-files -p "stemcells-ubuntu-xenial" -r "170.51" -i "364456" --accept-eula` and are facing this error : `Pivnet error: could not find release with 'id'=353376 for product with 'id' or 'slug'=233` . I noticed that this is the *0.0.49* version of pivnet . If i use a more recent version (*0.0.55* or newer , it works fine) . 
Can you fix the pb please , as we are stucked on our concourse pipeline .
Thanks

**Comment by pnikonowicz** [comment]
remove the `--accept-eula` flag. it is an undocumented and unsupported flag.

**Comment by erboucherie** [comment]
That's weird that it was working fine several weeks ago , and still works with newer versions of pivnet .

**Comment by waciuma4pivotal** [comment]
If you are seeing this error, you are on an old version of the CLI. Upgrading to the current version will return a more relevant error.

For context, the --accept-eula flag is meant for internal Pivotal use only. Its use by external users was unknown and has now been restricted. While old versions of the CLI handle this poorly, current releases will essentially ignore the flag. Implication for users:
- Accepting EULAs must be done on the network.pivotal.io site.
- After accepting a EULA on the website, downloads with the flag will proceed if using the current CLI, regardless of whether the `--accept-eula` flag is set. Downloads on the old CLI will always fail if the `--accept-eula` flag is set.

**Comment by a09-capf** [comment]
Hi team,

I faced same problem.
I use the [pivotal-cf/pcf-pipelines](https://github.com/pivotal-cf/pcf-pipelines) and that's pipeline still uses [the old CLI](https://github.com/pivotal-cf/pcf-pipelines/blob/v0.23.12/tasks/upload-product-and-stemcell/task.yml#L8) and [the --accept-eula flag](https://github.com/pivotal-cf/pcf-pipelines/blob/v0.23.12/tasks/upload-product-and-stemcell/task.sh#L63).

```
$ docker run -it pcfnorm/rootfs /bin/bash
root@24679cebe594:/# pivnet-cli --version
0.0.49
root@24679cebe594:/# pivnet-cli login --api-token="xxxxxxxxxxxxxx"
Logged-in successfully
root@24679cebe594:/# pivnet-cli download-product-files -p "stemcells-ubuntu-xenial" -r 170.51 -g "*azure*" --accept-eula
Pivnet error: could not find release with 'id'=353376 for product with 'id' or 'slug'=233
```

This is the reason why I face this problem, so I hope your team fix that pipeline.

Thanks.

**Comment by pnikonowicz** [comment]
Hi @a09-capf , if you have a pivotal representative that you or your company can work with, we can work with them to help fix this pipeline. You should reach out to them first as there is nothing that we can do from here. Let me know if you require additional assistance with this.

**Comment by a09-capf** [comment]
@pnikonowicz Thank you for response.
Our team already made a support case through the Pivotal Support and we are waiting for their response.
If there are any problems in communicating with them, I will come here again to get your assistance.

Thanks.
