### ISSUE TITLE
`Selected User Groups Only` in metadata not working

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/pivnet-resource#117]
We have the following metadata (snippet):

```
  availability: Selected User Groups Only
  user_group_ids:
    - 164
    - 255
```
However, when we upload our tile to pivnet with the above metadata, the tile is still admin only.

Didn't look too deep into it, but we found a slack thread describing the behavior of `pivnet-resource`:

- create new release
- foreach file in `file_glob`; do
- add file to release
- done

which seems like when the release is created, the file is not available yet. I thought when there is no file added to the release, the `Selected User Group Only` is not an option. Does that mean this is a bug in how `pivnet-resource` handles the release creation flow?

**Comment by rszumlakowski** [comment]
We'll look into this and get back to you @fredwangwang .

**Comment by rszumlakowski** [comment]
@fredwangwang  -  The last time we talked you informed me that you weren't seeing this problem anymore.  Can you please confirm if you have seen this problem again?

**Comment by fredwangwang** [comment]
Oh sorry, I meant to close this one a while ago... Somehow forgot. We are not seeing the issue anymore, closing now
