### ISSUE TITLE
README confusion around product_version

### ISSUE THREAD

**Issue by lurraca** [pivotal-cf/pivnet-resource#119]
I was trying to understand how does the product_version works and the text on the README confused me a little bit. The behaviour that I want is to 

> match all product version

but I am not sure if should set the property to `product_version: ""` or if I don't specify this property it will default to empty value?

https://github.com/pivotal-cf/pivnet-resource/blame/master/README.md#L76-L80

**Comment by rszumlakowski** [comment]
Hi @lurraca .  I'll look into your request and get back to you.

**Comment by rszumlakowski** [comment]
The `product_version` field is marked as optional.  We recommend omitting this field in order to match all product versions.
