### ISSUE TITLE
Supporting getting every release moving forward

### ISSUE THREAD

**Issue by Manifaust** [pivotal-cf/pivnet-resource#122]
RabbitMQ maintains three minor branches:
* 1.18.x
* 1.17.x
* 1.16.x

Our team (OSLO) has one pivnet resource for the entire RabbitMQ product. In other words, we don't configure the resource with version globbing. Currently there's no way for us to configure the resource to trigger for every minor release. The Pivnet resource will only obtain releases on the 1.18.x version line.

We want to be able to configure the pivnet resource to give us every release moving forward, no matter which version line it is.

**Comment by rszumlakowski** [comment]
As a workaround, could you create three instances of the Pivnet resource, one per minor branch of RabbitMQ that you want to track?

**Comment by Manifaust** [comment]
@rszumlakowski RabbitMQ is only one of close to thirty products we pull from. Also, the number of products grow dynamically. We don't know when these products add a new minor line.

On a larger scale, we want to know when any tile from any Pivotal products gets pushed to Pivnet.

**Comment by rszumlakowski** [comment]
The version matchers in the Pivnet resource are regular expressions.  Could you change your regular expression to match more than one minor product line.  I admit I have not tried this before.  I am just trying to think of possible workaround that you could try right away.

**Comment by xtreme-debbie-chen** [comment]
We have a workaround solution for the time being, but we are hoping to not have to rely on it in the future since it require manual triggering of the job.

**Comment by jtarchie** [comment]
This sounds like you are trying to build a resource, which acts like a resource.
Don't do this, because you'll end up reimplementing things that concourse provides for you, specifically version tracking.

**Comment by pivotal-kahin-ng** [comment]
We added a "last_updated" sort option on Pivnet Resource.  You can see the code changes in the commit https://github.com/pivotal-cf/pivnet-resource/pull/123.  The new sort is available in v0.31.37 of Pivnet Resource.  Please enjoy!
