### ISSUE TITLE
Encountering errors with latest-final tag on dockerhub

### ISSUE THREAD

**Issue by idoru** [pivotal-cf/pivnet-resource#133]
Hi, we've been using the docker image `pivotalcf/pivnet-resource:latest-final` happily in our pipelines, but it seems like it was broken recently... Here's some output from the failed run:

```
2020/09/10 16:42:01 PivNet Resource version: 0.31.47
2020/09/10 16:42:01 Creating download directory: /tmp/build/get
2020/09/10 16:42:01 Getting release for product slug: '<<<REDACTED>>>' and product version: '2019.25'
2020/09/10 16:42:03 Accepting EULA for release with ID: 716425
2020/09/10 16:42:03 Getting product files
2020/09/10 16:42:03 Getting file groups
2020/09/10 16:42:03 Getting image references
2020/09/10 16:42:03 Getting helm chart references
ERROR: no API endpoint matches 'products/<<<REDACTED>>>/releases/716425/helm_chart_references'
```

Fixing the tag to v1.0.1 works around this for us now, but this shouldn't be happening. Also, it's very odd that the version is reported as 0.31.47

**Comment by gerhard** [comment]
I've just hit this with PivNet Resource version: 0.31.48 & both Docker image versions v1.0.0 & v2.0.0. Trying v1.0.1 next.

**Comment by gerhard** [comment]
I'm hitting this issue with these pivnet-resource Docker versions: v1.0.0, v1.0.1 & v2.0.0:

```
Successfully pulled pivotalcf/pivnet-resource@sha256:2d974ce637b577341ce4fd6a01b60600d40a643c7d8de49e264f9aa782bd67f6.

2020/09/10 17:37:00.471322 PivNet Resource version: 0.31.48
2020/09/10 17:37:02.111606 Validating EULA: 'vmware_eula'
2020/09/10 17:37:03.599758 Validating release type: 'Major Release'
...
2020/09/10 17:37:04.745942 No release date found - using default release date - [map[release date:2020-09-10]]
2020/09/10 17:37:05.353589 Created new release with ID: 739282
...
2020/09/10 17:37:05.930895 Creating product file with remote name: REDACTED
2020/09/10 17:37:05.930973 Uploading /tmp/build/put/REDACTED
 14.93 MiB / 14.93 MiB [================================] 100.00% 15.71 MiB/s 0s

2020/09/10 17:37:06.881579 Successfully uploaded '/tmp/build/put/REDACTED
2020/09/10 17:37:09.956850 Adding product file: REDACTED
2020/09/10 17:37:10.585388 Polling product file: REDACTED
2020/09/10 17:37:16.053787 Product file: REDACTED async transfer complete
...
2020/09/10 17:37:19.073266 Adding product file: REDACTED with ID: 785295
2020/09/10 17:37:19.690426 Polling product file: REDACTED for async transfer - will wait up to 1h0m0s
2020/09/10 17:37:25.160999 Product file: REDACTED async transfer complete
ERROR: no API endpoint matches 'products/REDACTED/helm_chart_references'
```

**Comment by gerhard** [comment]
My issue was the `resource_type` config which was not working as expected in Concourse v6.5.1.

Given the following:

```yaml
resource_types:
  - name: pivnet
    source:
      repository: pivotalcf/pivnet-resource
      tag: v1.0.1
    type: docker-image
```

The docker image version that was being pulled was `v0.31.48`, as you can see in the output from my previous comment. You have a similar thing happening in your output @idoru, the pivnet-resource version is `0.31.47` in the output that you have shared.

This fixed it for me:

```diff
resource_types:
  - name: pivnet
    source:
      repository: pivotalcf/pivnet-resource
-      tag: v1.0.1
+      tag: latest-final
    type: docker-image
```

I am now seeing the right pivnet-resource version pulled, and the error disappeared:

```
..
2020/09/10 20:28:30.945802 PivNet Resource version: 1.0.1
...
2020/09/10 20:28:56.427793 Put complete
```

**Comment by idoru** [comment]
The output I shared where it shows `0.31.47` was from when I have the `tag` set to `latest-final`. 

When I set it to `v1.0.1` it works fine for me.

**Comment by idoru** [comment]
According to https://hub.docker.com/r/pivotalcf/pivnet-resource/tags right now, `latest-final` *should* be the same as `v2.0.0`

**Comment by khng** [comment]
> According to https://hub.docker.com/r/pivotalcf/pivnet-resource/tags right now, `latest-final` _should_ be the same as `v2.0.0`

That would be correct. I just tried it a few times with `latest-final` and I get this digest: `sha256:fe566ef2144e985de0715f70e7a99b1f021143e3185d6240d3df1832781b54c1` which is the same as using tag `v2.0.0`. 

Maybe there is a caching issue for it to pull `v0.31.47` when `latest-final` is set on your pipeline? Could you run your pipeline with `latest-final` again to see if the issue is still persisting?

**Comment by idoru** [comment]
I just tried `v2.0.0` and it works fine as well. So looks like our environment has some stale cache for `latest-final`. Closing. Thanks for your time.
