### ISSUE TITLE
md5 required when downloading non-software file types

### ISSUE THREAD

**Issue by scottfrederick** [pivotal-cf/pivnet-resource#35]
When performing a `get` on a tile release, the resource attempted to download the `.pivotal` file and the Open Source License `.txt` file. The resource gave an error when comparing the OSL file's calculated md5 against the expected md5, because the OSL file did not have an md5: 

`2016/09/28 15:33:42 Failed MD5 comparison for file: open_source_license_PCF-Service-Tile-Spring-Cloud_-1.1-_GA.txt. Expected , got d6f3fbad538edee63d7bf1a69a96370a`

According to the PivNet UI, only files of type "Software" require an md5: 

![screen shot 2016-09-28 at 11 26 55 am](https://cloud.githubusercontent.com/assets/60661/18922509/86544c84-856e-11e6-94b8-32516f200998.png)

It's an easy work-around to just add the md5 to documentation and OSL files, but it would be better if the PivNet expectations and the resource's expectations matched.

**Comment by robdimsdale** [comment]
@scottfrederick this is now fixed in [v0.23.0](https://github.com/pivotal-cf/pivnet-resource/releases/tag/v0.23.0) - thanks for the feedback!
