### ISSUE TITLE
downloads - EOF

### ISSUE THREAD

**Issue by zachgersh** [pivotal-cf/pivnet-resource#38]
So, in downloading the ERT we generally see an EOF every couple of downloads from Pivnet. S3 is inherently flakey and we should be retrying these downloads in the pivnet-resource.

cc @davewalter

**Comment by robdimsdale** [comment]
Sure thing, agreed. I think the best way is to extend https://github.com/pivotal-cf/go-pivnet/blob/master/extension/extended_client.go#L59 to return a `retryable` boolean, and callers (like the pivnet CLI and pivnet-resource) can choose how to handle that.

Do you have a better suggestion?

**Comment by robdimsdale** [comment]
We have some PRs that will address this: I will close this issue so that we can move the conversation to the PRs.

**Comment by robdimsdale** [comment]
The PRs got closed so I will reopen this so we don't lose the conversation

**Comment by robdimsdale** [comment]
The corresponding PRs have been merged so I will close this issue again.
