### ISSUE TITLE
execute concurrent downloads

### ISSUE THREAD

**Issue by zachgersh** [pivotal-cf/pivnet-resource#39]
Most of the files are going to be pretty large. It would be great if they were being concurrently downloaded in small chunks. Since s3 is the backing store we do already get content ranges from free.

cc @davewalter

**Comment by robdimsdale** [comment]
@zachgersh sounds great, how would you like to implement this? We get a link from pivnet which is a signed URL which we just `io.Copy` - how can we take advantage of the S3 features here?

**Comment by zachgersh** [comment]
I believe that pivnet eventually gives you back the signed cloud front URL
which should have accept ranges on it. Making a HEAD request to get that
URL instead of the masked one would probably allow us to get the content.

**Comment by robdimsdale** [comment]
Sounds good - feel free to work on that. I suspect you'd probably want to start around https://github.com/pivotal-cf/go-pivnet/blob/master/extension/extended_client.go#L77 - making the `HEAD` request here.

**Comment by zachgersh** [comment]
Yeah, I've already implemented something similar to this in the bosh.io
resource. most of this code is going to have to be replaced. You can check
it out here:

https://github.com/concourse/bosh-io-stemcell-resource/blob/master/boshio/boshio.go#L103

**Comment by robdimsdale** [comment]
I like it.

**Comment by zachgersh** [comment]
this has also now been fixed by:
https://github.com/pivotal-cf/pivnet-resource/commit/060707061630bca3610efef3f05c7c0a2b8bde88
