### ISSUE TITLE
globs failing to match anything

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf/pivnet-resource#45]
A glob that used to match in `v26.1` no longer matches.

**Comment by virtmerlin** [comment]
Seeing same issue:

2016/11/07 21:39:02 PivNet Resource version: 0.27.0
2016/11/07 21:39:02 Creating download directory: /tmp/build/get
2016/11/07 21:39:02 Getting release for product slug: 'elastic-runtime' and product version: '1.8.13'
2016/11/07 21:39:04 Accepting EULA for release with ID: 2799
2016/11/07 21:39:04 Getting product files
2016/11/07 21:39:04 Getting file groups
2016/11/07 21:39:06 Getting release dependencies
2016/11/07 21:39:07 Getting release upgrade paths
2016/11/07 21:39:07 Downloading files
2016/11/07 21:39:07 Filtering download links by glob
2016/11/07 21:39:07 Exiting with error: no match for glob: '*.pivotal'

Roll back to PivNet Resource version: 0.26.1 functions on wildcard string

**Comment by robdimsdale** [comment]
This should now be fixed with [v0.27.1](https://github.com/pivotal-cf/pivnet-resource/releases/tag/v0.27.1). Thanks for the prompt feedback.
