### ISSUE TITLE
Check scripts seem to hang intermittently

### ISSUE THREAD

**Issue by Osis** [pivotal-cf/pivnet-resource#51]
After a length of time, it seems like some check scripts will hang. There is no pattern with which resource hangs or the type on configuration that I can see. Just that if I leave them alone for a few hours, I can count at least one of them hanging.

Here is a [stack trace](https://github.com/pivotal-cf/pivnet-resource/files/625701/trace.txt) from the process once its killed.

**Comment by robdimsdale** [comment]
I've not seen that behavior before. It looks like something needs a timeout - possibly at the TCP level. Explicitly setting the TCP timeout is usually a good idea in golang anyway - we should do that.

Also, possibly related: https://github.com/concourse/concourse/issues/785#issuecomment-262029705

**Comment by Osis** [comment]
For context, this Concourse installation is on GCP and I've tried MTU settings of 1500, 1450, and 1430.

**Comment by joshzarrabi** [comment]
The concourse team's dogfood server is also seeing this a lot, to the point where people are complaining.

Is there anything we can do to help you fix this, @robdimsdale ?

**Comment by robdimsdale** [comment]
@Osis the latest release of pivnet-resource (0.27.4) includes timeouts which should hopefully avoid this issue with the `check` hanging indefinitely. I'm going to close this issue but please feel free to reopen if you see it again or have any further information.
