### ISSUE TITLE
Progress bar only shows up for the first file downloaded from a release

### ISSUE THREAD

**Issue by davewalter** [pivotal-cf/pivnet-resource#54]
Our CI just started consuming v0.27.4 and I noticed that there is an issue with the file download progress bar when retrieving multiple files from a release. Here is the output from downloading ERT 1.8.23:

```
2016/12/21 00:47:13 PivNet Resource version: 0.27.4
2016/12/21 00:47:13 Creating download directory: /tmp/build/get
2016/12/21 00:47:13 Getting release for product slug: 'elastic-runtime' and product version: '1.8.23'
2016/12/21 00:47:16 Accepting EULA for release with ID: 3508
2016/12/21 00:47:16 Getting product files
2016/12/21 00:47:17 Getting file groups
2016/12/21 00:47:19 Getting release dependencies
2016/12/21 00:47:19 Getting release upgrade paths
2016/12/21 00:47:19 Downloading files
2016/12/21 00:47:19 Filtering download links by glob
2016/12/21 00:47:19 Downloading filtered files
2016/12/21 00:47:19 Downloading: 'PCF Elastic Runtime 1.8 License' to file: '/tmp/build/get/open_source_license_PCF-Elastic-Runtime-1.8.txt'
 1.71 MB / 1.71 MB  100.00% 3s11ss
2016/12/21 00:47:25 Downloading: 'DiegoWindows' to file: '/tmp/build/get/DiegoWindows-1.8.5.zip'
2016/12/21 00:47:30 Downloading: 'PCF Cloudformation for AWS Setup' to file: '/tmp/build/get/pcf_1.8.23-build.2_cloudformation.json'
2016/12/21 00:47:33 Downloading: 'PCF Elastic Runtime' to file: '/tmp/build/get/cf-1.8.23-build.2.pivotal'
```

It looks like there might be a rendering issue.

**Comment by davewalter** [comment]
Interestingly, even if CI only downloads a single file from PivNet, the elapsed time in the progress bar is still messed up:
```
2016/12/21 16:24:25 Downloading filtered files
2016/12/21 16:24:25 Downloading: 'PCF Elastic Runtime' to file: '/tmp/build/get/cf-1.8.9-build.13.pivotal'
 4.63 GB / 4.63 GB  100.00% 6m32ss2s
2016/12/21 16:30:59 Calcuating MD5 for downloaded files
```

**Comment by robdimsdale** [comment]
Yeah it's interesting. I think there's two issues here - one is that the progress doesn't seem to render properly - the `===` is missing. The second issue is that the progress bar doesn't seem to render at all for all products after the first. It seems likely that these issues are related. Not sure what's going on yet.

**Comment by robdimsdale** [comment]
Yeah it's interesting. I think there's two issues here - one is that the progress doesn't seem to render properly - the `===` is missing. The second issue is that the progress bar doesn't seem to render at all for all products after the first. It seems likely that these issues are related. Not sure what's going on yet.

**Comment by robdimsdale** [comment]
Fixed - the progressbar library needed to explicitly be told the width of the terminal as it isn't a TTY. This will be in the next release.
