### ISSUE TITLE
Feature request: Ability to consume a release from PivNet without downloading any files from it

### ISSUE THREAD

**Issue by davewalter** [pivotal-cf/pivnet-resource#55]
We use the appearance of new releases on PivNet to trigger parts of our CI, but the triggering job doesn't need to download any files from the release (it just checks the metadata.json file).

It would be great if there was a flag in the get params that prevented any files from being downloaded. I know that I could achieve this by specifying a glob that is guaranteed to not match anything, but this seems like a hack.

**Comment by robdimsdale** [comment]
We already support this with `globs: []` - I added explicit instructions to the README with https://github.com/pivotal-cf/pivnet-resource/commit/314b22d9b444b0d7c1fe9f1a4c4601c3d3986bd9
