### ISSUE TITLE
Retry Auth

### ISSUE THREAD

**Issue by Osis** [pivotal-cf/pivnet-resource#57]
I've been getting these 403s a couple times a day for not constant enough to determine a pattern. Might be an edge case around auth an retying downloads?

```
2017/01/11 15:30:58 Downloading: 'PCF Metrics' to file: '/tmp/build/get/apm-1.2.4.pivotal'
 983.72 MB / 1.07 GB   90.00% 3m17ss
2017/01/11 15:34:16 Download failed: failed during retryable request: during GET unexpected status code was returned: 403
ERROR: failed during retryable request: during GET unexpected status code was returned: 403
```

**Comment by zachgersh** [comment]
@Osis - interesting, we should probably add more debug logging around the retryable request so we can see what is going on.

**Comment by robdimsdale** [comment]
@Osis we've improved the retry logic a lot and seen improvements in various teams' pipelines, so I'm going to close this out, but please feel free to re-open if you continue to observe issues.
