### ISSUE TITLE
Product download stuck at 0%.

### ISSUE THREAD

**Issue by pdelagrave** [pivotal-cf/pivnet-resource#59]
Hi

We upgraded from 0.26.1 to the latest docker image 0.30.0 today and we see this happening very frequently with the bigger product. 
p-mysql which is about 1gb also has this problem but the download eventually start.

We tried the default region and us-east-2 too, with the same results.
We can provide all kind of concourse (2.6.0) logs if necessary.

```
2017/01/24 22:49:27 PivNet Resource version: 0.30.0
2017/01/24 22:49:27 Creating download directory: /tmp/build/get
2017/01/24 22:49:27 Getting release for product slug: 'elastic-runtime' and product version: '1.10.0-alpha.1'
2017/01/24 22:49:28 Accepting EULA for release with ID: 3840
2017/01/24 22:49:28 Getting product files
2017/01/24 22:49:28 Getting file groups
2017/01/24 22:49:29 Getting release dependencies
2017/01/24 22:49:29 Getting dependency specifiers
2017/01/24 22:49:29 Getting release upgrade paths
2017/01/24 22:49:29 Downloading files
2017/01/24 22:49:29 Filtering download links by glob
2017/01/24 22:49:29 Downloading filtered files
2017/01/24 22:49:29 Downloading: 'PCF Elastic Runtime' to file: '/tmp/build/get/cf-1.10.0-build.79.pivotal'
 0 B / 7.86 GB [-------------------------------------------------------]   0.00%
```

**Comment by robdimsdale** [comment]
You mention that the download eventually starts - if you leave it alone for a while does it succeed? If so, you may be running into a known issue that the download progress bar is extremely non-linear; it spends most of its time at 0% and rapidly shoots to 100%.

If you can find out how long it takes to download the product with `v0.26.1` and wait that long with `v0.30.0`, does the product download?

cc @zachgersh @dannysullivan

**Comment by robdimsdale** [comment]
see also existing story to improve the product bar UI: https://www.pivotaltracker.com/story/show/135648503

**Comment by pdelagrave** [comment]
I came in this morning and the download was done and the same `get` task is now stuck at:
```
2017/01/24 23:15:01 Downloading: 'PCF Elastic Runtime' to file: '/tmp/build/get/cf-1.10.0-build.79.pivotal'
 7.86 GB / 7.86 GB [============================================] 100.00% 26m38s
2017/01/24 23:41:41 Calcuating MD5 for downloaded files
2017/01/24 23:41:59 MD5 matched for all downloaded files
2017/01/24 23:41:59 Get complete
2017/01/24 23:41:59 Creating metadata
2017/01/24 23:41:59 Writing metadata files
```

So it took 26 minutes from the start to the end of the download, which was spent in main part displaying 0%.
I hijacked the task yesterday when it was stuck and the file size was 0 bytes, depending how the chunk download occurs it might be actually downloading but doesn't update the logs nor write to the file until a certain moment.

**Comment by robdimsdale** [comment]
Ok, so the download eventually succeeded. That's good to know. Yes, we don't update until the chunk is complete - that often takes a long time. The non-linearity of the progress bar is a known issue (see https://www.pivotaltracker.com/story/show/135648503) but the download should actually be more reliable than it was before, due to some new retry logic.

I'm going to close this issue so we don't have multiple stories tracking this work. Please feel free to open if I've mischaracterized what you're seeing, or if you have more information to add.

**Comment by robdimsdale** [comment]
@pdelagrave just an FYI, the latest pivnet-resource (and CLI) should have much better progress bar feedback here.

**Comment by pdelagrave** [comment]
We've been using it and the feedback is really useful!
Thanks
