### ISSUE TITLE
MD5 check is case sensitive

### ISSUE THREAD

**Issue by guidowb** [pivotal-cf/pivnet-resource#62]
Can't download a file because the case of the MD5 signature doesn't match:
```
ERROR: MD5 comparison failed for downloaded file: '/tmp/build/get/flo-spring-xd-admin-ui-client-1.3.1.RELEASE.zip'. Expected (from pivnet): '7497FFD1F2C92CAF016C49CA071B9CEF' - actual (from file): '7497ffd1f2c92caf016c49ca071b9cef'
```

**Comment by zachgersh** [comment]
That's really funny because the MD5 is exactly the same but lowercase.

```
7497FFD1F2C92CAF016C49CA071B9CEF - The one from pivnet
7497ffd1f2c92caf016c49ca071b9cef - The one go generates
```

I don't see this on releng. Are you all capitalizing your MD5's when you paste them into pivnet?

**Comment by robdimsdale** [comment]
@guidowb I've never seen a MD5 that's upper-cased, and when I research it I see a slight preference for lower-casing it. We can obviously lower-case it, but you might reach out to the product authors of the affected product to let them know that an upper-cased MD5 is unusual, and see if they have a good reason why it's like that.

We can use this issue to drive out the case-insensitive check.

**Comment by crawsible** [comment]
@guidowb We're going to handle this on the Pivnet side[1] by always outputting MD5s in lowercase regardless of how they were entered, probably some time tomorrow or early next week. In the meantime, if this is urgent, I'd echo Rob's call to reach out to the product authors to downcase the product file's MD5.

---

[1] https://www.pivotaltracker.com/story/show/138925723

**Comment by guidowb** [comment]
I don't know who the product authors are. It's not urgent for me, it's just silly. From my perspective anyone who compares MD5 signatures should not consider them different if the only difference is case. The check should be case insensitive.

**Comment by crawsible** [comment]
@guidowb Both are probably true. Capitalized MD5s are non-standard and probably should be avoided, but they *are* valid, and should probably be checked case-insensitively. Given that we're standardizing output on Pivnet, though, I don't think it's a priority to fix it on the pivnet-resource side as well.
