### ISSUE TITLE
EULA not automatically be accepted anymore

### ISSUE THREAD

**Issue by cityfarmer** [pivotal-cf/pivnet-resource#74]
Hi,
Pivnet-resource stopped automatically accepting EULA this week and release downloads are failing.  I tried switching Account API Tokens and regenerating tokens but I get the same error.  If I manually accept the EULA, the download succeeds.  

2017/05/16 21:55:18 PivNet Resource version: 0.30.8
2017/05/16 21:55:18 Creating download directory: /tmp/build/get
2017/05/16 21:55:18 Getting release for product slug: 'elastic-runtime' and product version: '1.10.8'
2017/05/16 21:55:19 Accepting EULA for release with ID: 5334
ERROR: user with email 'clinton.w.propst.ctr@nga.mil' has not accepted the current EULA for release with 'id'=5334. Please manually accept the EULA via this URL: https://network.pivotal.io/products/60/releases/5334/eulas/120

Any help is appreciated.  

Thanks,
Clinton

**Comment by jimbosity** [comment]
Hi Clinton - 

We're now requiring Pivnet API users to accept EULAs manually, so this is expected. It seems like you've been able to accept the EULA and download the files. 

You should only have to do this once per product (and very occasionally after that) - if you're seeing that you're required to accept the EULAs more often, please let me know.

Jim

**Comment by thagh05t** [comment]
```
[download-product-files command options]
      -p, --product-slug=        Product slug e.g. p-mysql
      -r, --release-version=     Release version e.g. 0.1.2-rc1
      -i, --product-file-id=     Product file ID e.g. 1234
      -g, --glob=                Glob to match product name e.g. *aws*
      -d, --download-dir=        Local directory to download files to e.g. /tmp/my-file/ (default: .)
          --accept-eula          Automatically accept EULA if necessary (Available to select users only)
```

How do I become a 'select user'?

**Comment by xtreme-debbie-chen** [comment]
@thagh05t Automatic EULA acceptance is only available for pivots.

**Comment by thagh05t** [comment]
What is a pivot, and how do I become one?

**Comment by xtreme-debbie-chen** [comment]
@thagh05t For legal reasons, you have to be a pivotal employee to be able to have pivnet-resource automatically accept the EULA. Otherwise, it will give you a url that you can follow to accept the EULA.

**Comment by thagh05t** [comment]
My problem with this is when purchasing, and during the dojo, I was told i
could completely automate the installation, which if I am unable to accept
eulas introduces a manual step.

**Comment by tiffjordan** [comment]
Thanks for this feedback @thagh05t. We are in progress of working with the legal team to see what improvements we may be able to make, but no changes have been finalized yet. I'll reach out to our upstream teams about this messaging to ensure the correct expectations are set up front. Any chance you would be interested in providing feedback on any upcoming changes we plan to introduce?

**Comment by pnikonowicz** [comment]
You only have to accept the EULA once per major version. Are you seeing that you have to accept more than once?

**Comment by thagh05t** [comment]
Alright, will do it.
