### ISSUE TITLE
Typo in message

### ISSUE THREAD

**Issue by henderjm** [pivotal-cf/pivnet-resource#76]
Should say calculating but says 'Calcuating' 😁 
https://github.com/pivotal-cf/pivnet-resource/blob/19cc305280f8ec57bdd650bbf77aa79568eaade0/in/in_command.go#L403

**Comment by dannysullivan** [comment]
Thanks for the report - we've pushed the fix and will ship the new resource version shortly.

**Comment by jchesterpivotal** [comment]
Closing as this was fixed some time ago.
