### ISSUE TITLE
`product_version` docs say it's a regex, but in practice, it looks like it requires a glob?

### ISSUE THREAD

**Issue by geofffranks** [pivotal-cf/pivnet-resource#81]
On the readme for this resource, `product_version` is described as being a regex. However, using the regex `^Go.*`, I get no versions back. https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-buildpacks/pipeline.yml seems to show the values as being blobs instead.

Can the docs be updated for this?

**Comment by jchesterpivotal** [comment]
It's a little misleading but it's [definitely using regexes internally](https://github.com/pivotal-cf/pivnet-resource/blob/360f73055f87c74bd0403e32c43da4805d30e31c/filter/filter.go#L40).

The search space is pretty small and it's surprisingly easy to come up with something that looks like a glob, but is actually a regex that matches anyhow. For example, [this line from the linked pipeline](https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-buildpacks/pipeline.yml#L49):

```    
    product_version: Go*
```

Doesn't say "`Go` followed by anything", as a glob would. It says "`G` followed by zero or more `o`s". [It will match](http://regexr.com/3h8ad) with `Go`, `Gooooo` or `Go Version 1.1.111` etc.

I'm not sure why the `^` start-of-line matcher isn't working for you. Does it work without it?

**Comment by geofffranks** [comment]
Ah right, golang uses weird escape chars for that - \Q I think.  I'll play around and see what I get. Thanks!

**Comment by geofffranks** [comment]
Nope, that's not right. Something else seems to be going on, but I'll re open a new issue if it's not operator etror
