### ISSUE TITLE
Debug log

### ISSUE THREAD

**Issue by avasseur-pivotal** [pivotal-cf/pivnet-resource#83]
I see this resource has debug logs
How could I turn them on in my pipeline or Concourse server?

**Comment by ddadlani** [comment]
Hi @avasseur-pivotal, there currently isn't any way to do this. Do you have a use case that requires debug logs to be turned on?

**Comment by robdimsdale** [comment]
The verbose/debug logs are written to a file on the container. I can't remember the exact location anymore, but you can access them via `fly intercept`.

**Comment by xtreme-debbie-chen** [comment]
You can now set `verbose: true` to source configuration of the resource to get it to output the verbose logs.
