### ISSUE TITLE
Segmentation Violation while downloading PCF Elastic Runtime tile

### ISSUE THREAD

**Issue by nikhilay** [pivotal-cf/pivnet-resource#85]
2017/12/27 08:46:57 PivNet Resource version: 0.31.5
2017/12/27 08:46:57 Creating download directory: /tmp/build/get
2017/12/27 08:46:57 Getting release for product slug: 'elastic-runtime' and product version: '1.11.21'
2017/12/27 08:46:59 Accepting EULA for release with ID: 9708
2017/12/27 08:46:59 Getting product files
2017/12/27 08:47:00 Getting file groups
2017/12/27 08:47:00 Getting release dependencies
2017/12/27 08:47:01 Getting dependency specifiers
2017/12/27 08:47:01 Getting release upgrade paths
2017/12/27 08:47:02 Getting upgrade path specifiers
2017/12/27 08:47:02 Downloading files
2017/12/27 08:47:02 Filtering download links by glob
2017/12/27 08:47:02 Downloading filtered files
2017/12/27 08:47:02 Downloading: 'PCF Elastic Runtime' to file: '/tmp/build/get/cf-1.11.21-build.3.pivotal'
1.11 GiB / 8.11 GiB [=====>-------------------------------------] 13.66% 1m58spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x62e2bc]

goroutine 122 [running]:
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download.Client.retryableRequest(0x848fa0, 0xc42005f560, 0x849e20, 0xc4200129d0, 0x84e180, 0xc4204e54a0, 0x84b120, 0xc4200be5a0, 0xc420564d80, 0x237, ...)
/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go:165 +0x27c
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download.Client.Get.func1(0x704a485500000008, 0x70a688)
/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/download/downloader.go:93 +0xb3
github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420387240, 0xc420580000)
/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup.(*Group).Go
/tmp/build/80754af9/gopath/src/github.com/pivotal-cf/pivnet-resource/vendor/github.com/pivotal-cf/go-pivnet/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

connection: process error: the exitcode file is empty

**Comment by robdimsdale** [comment]
I think that this is related to https://github.com/pivotal-cf/pivnet-resource/issues/84

**Comment by pnikonowicz** [comment]
to repro:  run the pivnet resource and point it to a disk that is full. on linux, reference `/dev/full`  on a mac, you can mount a full disk in ram by running:

```
#!/usr/bin/env bash

VOLUME=FULL_DISK
DEVICE=$(hdiutil attach -nomount ram://64)
diskutil erasevolume MS-DOS ${VOLUME} ${DEVICE}
touch "/Volumes/${VOLUME}/full"
cat /dev/zero > "/Volumes/${VOLUME}/space"
```

**Comment by kartiklunkad26** [comment]
This issue will be fixed in the next release of pivnet-resource!
