### ISSUE TITLE
Pivnet-resource should optionally trigger on version changes only

### ISSUE THREAD

**Issue by jacknewberry** [pivotal-cf/pivnet-resource#90]
Symptom:
We use pivnet-resource in the PCF Redis team to trigger our pipelines when new stemcell patches are released. 

We use `tag: latest-final` of pivnet-resource from docker hub.

Current Behaviour:
Multiple changes to source metadata causes our pipelines to run multiple times with the same stemcell. The last stemcell (3445.28) triggered 5 times across several hours.

We suspect that in most cases the pivnet resource should not trigger on changes to metadata. We want the resource to trigger only on changes to the minor version.

Suggestion:
- Add an 'ignore_metadata_changes' flag to the source configuration. 
This would allow teams that wish to check metadata to continue to do so, while improving the experience for teams interested in actual releases.

cc: @mrosecrance

**Comment by jacknewberry** [comment]
Yes, with `ignore_metadata_changes: true`, I think any changes that are not file changes should be ignored.

**Comment by tiffjordan** [comment]
@jacknewberry If you log in without an admin or special access account, does that help resolve the issue as well?

**Comment by jacknewberry** [comment]
Hi Tiffany,

I think using a user with reduced permissions has fixed this for us. We
won't know for certain until a new stemcell is released.

It is a little less than ideal. We now need to maintain separate users to
check pivnet, and to upload to pivnet. I'm sure we will manage.

Jack

**Comment by davewalter** [comment]
Hi @tiffjordan,

We definitely see this when our PMs make changes to our releases once they are public. We've gotten around it by checking the version of the triggering resource against an external file to see if we have already performed the desired action, but it would be nice if we didn't have to do this.

Regards,
Dave

**Comment by pnikonowicz** [comment]
I will bring this to our PM's attention.
Closing issue.
Marking as wont' fix.

This is not permanent but a reflection of the current status. Please feel free to comment or reopen.
