### ISSUE TITLE
Downloads such as PAS can 'hang' at 99% completion

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/pivnet-resource#91]
On Feb 26, 2018 the Toolsmiths team noticed that 8 pipelines were trying to download the PAS tile, and were stalled out at 99% completion. Most environments were stuck in this way for 5 hours or longer. Here are the logs:

```
2018/02/26 12:49:52 PivNet Resource version: 0.31.7
2018/02/26 12:49:52 Creating download directory: /tmp/build/get
2018/02/26 12:49:53 Getting release for product slug: 'elastic-runtime' and product version: '2.0.6'
2018/02/26 12:49:54 Accepting EULA for release with ID: 52010
2018/02/26 12:49:55 Getting product files
2018/02/26 12:49:56 Getting file groups
2018/02/26 12:50:00 Getting release dependencies
2018/02/26 12:50:03 Getting dependency specifiers
2018/02/26 12:50:03 Getting release upgrade paths
2018/02/26 12:50:04 Getting upgrade path specifiers
2018/02/26 12:50:04 Downloading files
2018/02/26 12:50:04 Filtering download links by glob
2018/02/26 12:50:04 Downloading filtered files
2018/02/26 12:50:04 Downloading: 'Pivotal Application Service' to file: '/tmp/build/get/cf-2.0.6-build.3.pivotal'
 7.77 GiB / 7.81 GiB [=================================================]  99.46%
interrupted
```

It seems reasonable that the downloads will occasionally fail due to cloudiness, but we're not sure of the best place to have re-try logic. This is also a 'hang', not a fail and you can see we `interrupted` it. Would be great if the PivNet resource could detect the 'hung' download, and we didn't have to do anything :)

I would also be okay modifying our pipelines, so that we set maybe a max time, and have it re-try if the max time for the job has expired. Would be great to get guidance on this issue, though.

Thanks!!
Mike J
PM@Toolsmiths

**Comment by mjj209** [comment]
I saw there have been some pivnet changes recently, but we also had 7 failures on 28-Feb-2018.

**Comment by tiffjordan** [comment]
Thanks for sharing this information Mike. I'll move the tracker story to our pivotal network backlog for review.

**Comment by mjj209** [comment]
We haven't seen this issue lately, dropping this down in the Toolsmith's backlog.

**Comment by xtreme-james-thomson** [comment]
Hi!

Recently we've been seeing this exact issue on a few of our pipelines, only with PAS... Usually it stalls out between 90%-99.9%.

We went inside the container, and we were able to verify the actual downloaded asset was the exact size as the actual file manually downloaded from pivnet.

Thanks!

**Comment by ddadlani** [comment]
We believe that this issue is related to the following concourse issues:

`https://github.com/orange-cloudfoundry/cf-ops-automation/issues/106`
`https://github.com/concourse/concourse/issues/456`

Closing this issue as there is no anticipated work on our end.
