### ISSUE TITLE
ERROR: invalid character 'B' after top-level value

### ISSUE THREAD

**Issue by michelleheh** [pivotal-cf/pivnet-resource#93]
While uploading a product to PivNet, we received the following error:

```
...
2018/03/12 18:10:11.324316 Product file: 'Pivotal Application Service' async transfer incomplete
2018/03/12 18:10:24.323960 Product file: 'Pivotal Application Service' async transfer incomplete
2018/03/12 18:10:24.415105 Product file: 'Pivotal Application Service' async transfer incomplete
2018/03/12 18:10:27.300199 Product file: 'Pivotal Application Service' async transfer incomplete
ERROR: invalid character 'B' after top-level value
```

We've see a similar error in other resources (invalid character '/' after top-level value) which was caused by the resource outputting non-JSON data to STDOUT. Maybe a wayward debug statement?

**Comment by ddadlani** [comment]
@michelleheh Could you give us some more context on how often this error occurs? 

How often does this occur?

If you reupload immediately after seeing this error, does the error persist or does this second attempt work as expected?

Are there any particular products or product files that are affected by this issue?

**Comment by pnikonowicz** [comment]
Closing issue. 

Please reopen if you are still having this problem.

**Comment by Sophichia** [comment]
Hi there, we just encountered this error after a `pivnet login --api-token XXXXXX`. Wanted to surface this for you guys.

**Comment by rszumlakowski** [comment]
Hi @Sophichia : Are you using the pivnet-resource or the pivnet API?  It's not typical to use the `pivnet login` command when using the pivnet-resource.

**Comment by anlijie** [comment]
I also encountered this problem, I sent the http request to get the json format file stitching url, because the url stitching has spaces, then, I removed the space, just fine
