### ISSUE TITLE
Pulling "real" product version in without downloading entire product?

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/pivnet-resource#94]
When staging a product in automated tile upgrades ([context is I'm working on pipelines to do selective-deploys](https://github.com/aegershman/pcf-pipelines-selective-deploy)), I need the `product_name` and the exact `product_version`. In order to get these fields, I need to extract them from the contents of the `*.pivotal`. But here's the thing: all I need are the text values for `product_name` and `product_version`. I don't actually need the product itself. The product has already been uploaded into the Opsman. In order to _stage_ that uploaded product, I need a way to get the exact product version to pass to the Opsman.

[Here's the task I'm working with:](https://github.com/aegershman/pcf-pipelines-selective-deploy/blob/master/tasks/stage-product/task.sh)

```bash
#!/bin/bash

set -eu
[ 'true' = "${DEBUG:-}" ] && set -x

# Very much inspired by pcf-pipelines stage-product task
# https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/stage-product/task.sh

# Should the slug contain more than one product, pick only the first.
FILE_PATH=$(find ./pivnet-product -name "*.pivotal" | sort | head -1)
unzip "$FILE_PATH" metadata/*

PRODUCT_NAME="$(
	cat metadata/*.yml |
		grep '^name' |
		cut -d' ' -f 2
)"

# I know, this is kind of bonkers. But here's the deal:
# We have to account for all these possible values (and maybe more?):
# product_version: '1.12.9-beta.11'
# product_version: 1.12.9-beta.11
# product_version: "1.12.9-beta.11"
# product_version: '1.12.9'
# product_version: 1.12.9
# product_version: "1.12.9"
# ... So that's what the weird tr -d is for
DESIRED_VERSION=$(
	cat metadata/*.yml |
		grep '^product_version' |
		cut -d' ' -f 2 |
		tr -d "'\""
)

om-linux \
	--target "https://${OPSMAN_DOMAIN_OR_IP_ADDRESS}" \
	--client-id "${OPSMAN_CLIENT_ID}" \
	--client-secret "${OPSMAN_CLIENT_SECRET}" \
	--skip-ssl-validation \
	stage-product \
	--product-name "$PRODUCT_NAME" \
	--product-version "$DESIRED_VERSION"
```

Also, when I refer to the "exact" product_version, [I'm referring to the fact that some products, such as p-healthwatch](https://network.pivotal.io/products/p-healthwatch/), have product versions that look like `p-healthwatch-1.1.7-build.11`, even though their pivnet version is `p-healthwatch-1.1.7`. So as far as I can tell, the only way to get the "real" product version is to download the entire `product.pivotal` file, unzip it, and extract the `metadata/product.yml` ([I wrote more about this problem in this issue here](https://github.com/aegershman/pcf-pipelines-selective-deploy/issues/21))

I know this is a long shot & I realize this is more of a blanket question than an "issue", but if anyone has any advice or suggestions I really appreciate it!

**Comment by davewalter** [comment]
Hi @aegershman 

You could curl the Ops Manager `/api/v0/available_products` API endpoint to retrieve the list of products (with versions) that are available to stage. You could also use the `om available-products` [command](https://github.com/pivotal-cf/om/tree/master/docs/available-products) if you want an easy to consume CLI.

We are also contemplating updating the `om stage-product` command to accept a version of `latest` that would semantically determine which product version to stage.

Hope this helps.
Dave

**Comment by aegershman** [comment]
some notes:

`om` now has a `tile-metadata` command. This allows you to cleanly do the following in a Concourse task:

```bash
om stage-tile \
--product-name $(om tile-metadata -p product.pivotal --product-name) \
--product-version $(om tile-metadata -p product.pivotal --product-version) 
```

However, it still requires downloading the _entire_ `*.pivotal` product just to run that command.

If there were a way for the `product-name` and `product-version` to be specified in the `metadata.yml`, you could get those params without incurring the network cost of DLing the entire thing. E.g.:

```yaml
- get: pivnet-product
   params:
      globs:
       - []  # would still make pivnet-product/metadata.yml available for later tasks
- task: stage-product
   ...
```

thoughts/ideas/critiques/rebuffs/etc. are welcome

**Comment by aegershman** [comment]
Absolutely. 

Could be solved with `om stage-product --product=<path-to-product.pivotal>`, or `om stage-product --product-name=$(om tile-metadata -p <path-to-product.pivotal> --product-name`, though the issue is that in order to get the `--product=*.pivotal`, you have to download the entire product, even though it's just a tiny snippet of text.

So if you already have the tarball uploaded/staged into opsmgr, the only way to _reference_ that product is to either:
1. manually store the `product-name/product-version` as a param somewhere else
2. download the entire product again (which could be many gigs depending on product), just so the `product-name/product-version` can be referenced

if the `product-name/product-version`, etc., were stored in the `metadata.yml`, the `pivnet` resource could get all this data without having to download the entire product.

thanks for your time & consideration

**Comment by pnikonowicz** [comment]
I will forward this issue to our PM's. 
Closing issue as "won't fix" 
Will reopen if needed. 
Feel free to comment or reopen if you feel so.
