### ISSUE TITLE
Testing network.pivotal.io replacement in China

### ISSUE THREAD

**Issue by bmhkb4** [pivotal-cf/pivnet-resource#96]
Hey guys, I am testing a local content store in china for a few select .pivotal files (the big ones).  I have my concourse job here in the U.S. copying them over to my Chinese web server where I have a simple nginx server running a static content endpoint.  I tried changing my "endpoint" variable to point to the location that I am able to curl from but it doesn't appear to work.  I get a:

> resource script '/opt/resource/check []' failed: exit status 1
> 
> stderr:
> 2018/06/28 21:18:20 Exiting with error: invalid character '<' looking for beginning of value

Any ideas?  I turned on auto indexing on the web server so I can view the directory via a browser or curl.  What am I missing?

**Comment by vitakras** [comment]
@bmhkb4 Hi, I am confused as to why you are changing the `endpoint` variable?

**Comment by bmhkb4** [comment]
Because Chinese internet sucks and our servers can't download large tiles like PAS unless we go over our company vpn.

**Comment by pivotal-ivan-wang** [comment]
The `endpoint` variable should only be pointing to a pivnet environment. (It's sometimes used to point to our internal integration or acceptance environments for example). Anything else like a custom server would be outside the scope of the functionalities of pivnet resource.

**Comment by pivotal-ivan-wang** [comment]
Closing this issue for now since there are no foreseeable changes for this on the side of pivnet-resource. Download issues in China has been escalated.
