### ISSUE TITLE
Prevent triggering on timestamp changes

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/pivnet-resource#97]
If a pivnet product is re-released with a new timestamp, it triggers a new build. Even if the product version is exactly the same, if the time stamp changes, it counts as a new version in Concourse.

Is there a way to prevent this from happening? I only want Concourse to register new product versions based on `semver`, regardless of if the timestamp has changed.

Here are two examples of our pipeline automation being triggered by timestamp changes on the same stemcell version. These are just two examples but this same thing has happened on multiple pivnet stemcell releases. (The same stemcell version was re-released due to a mixup of some kind where the stemcell was made available on pivnet, then somehow accidentally pulled from pivnet, then re-released):

`3541.34` initially released on `6-20` but re-released on `7-02`:
![screen shot 2018-07-03 at 10 26 42 am](https://user-images.githubusercontent.com/5619476/42229330-d9084f6a-7eab-11e8-8b5d-f91bc21ed871.png)
![screen shot 2018-07-03 at 10 26 23 am](https://user-images.githubusercontent.com/5619476/42229335-dd9a13b0-7eab-11e8-96ad-2b79a4d5fa31.png)

`3468.51` initially released on `6-20` but re-released on `7-02`:
![screen shot 2018-07-03 at 10 27 05 am](https://user-images.githubusercontent.com/5619476/42229406-0a7d3a10-7eac-11e8-8e16-73633d49870b.png)
![screen shot 2018-07-03 at 10 26 58 am](https://user-images.githubusercontent.com/5619476/42229410-0cec61e0-7eac-11e8-87b9-5f4f87c43db0.png)

I know it's not a *huge* deal since the product version itself hasn't changed, but I'd like to prevent this from happening.

Thanks a ton, I appreciate your time and work.

**Comment by vitakras** [comment]
We are currently working on a feature to prevent tile authors from being able to re-release the same tile after they have made it available to the public. That may indirectly address this issue.

**Comment by pivotal-ivan-wang** [comment]
Hi @aegershman, our feature to prevent tile authors from adding or removing files from a release published to All Users has been implemented. This should help with the problem you were experiencing. For now, we will close this issue, but if your problem persists, please let us know!

**Comment by aegershman** [comment]
@pivotal-ivan-wang by the way it looks like `p-event-alerts-1.2.3` was initially released on `9/5` and then re-released today (9/11). This caused our pipelines to trigger apply-changes. Not a big deal, but figured I'd share since I'm not sure if this is an anomaly on our end or possibly an error:

9-5
![event-alerts-9-5](https://user-images.githubusercontent.com/5619476/45384599-13855700-b5d4-11e8-95fc-aaf0057d68ef.png)

9/11 (today)
![event-alerts-9-11](https://user-images.githubusercontent.com/5619476/45384600-13855700-b5d4-11e8-922a-86719a296c07.png)

**Comment by xtreme-debbie-chen** [comment]
Thank you for notifying us. This release was recently modified (with our knowledge) to add some new files to it. So that it is probably why it re-triggered your pipeline.

**Comment by aegershman** [comment]
No worries at all, just letting you know in case it wasn't intentional 👍 thank you for your response
