### ISSUE TITLE
pivnet-resource put overrides products with same slug and version

### ISSUE THREAD

**Issue by cdutra** [pivotal-cf/pivnet-resource#98]
Currently this behavior is error prone given an mistake in pipeline configuration or even accidental triggers could result in overriding the product with the same version.

The suggestion is to add a flag `override` that when set to `true` will allow the put to override the product and, when `false` will error during the put with a proper error message: `Product with :slug and :version already exists!`. By default `override` is `false`.

**Comment by pivotal-ivan-wang** [comment]
This feature has been implemented. Closing Issue.
